class States:
    IDLE="IDLE"; CUSTOMER_NAME="CUSTOMER_NAME"; CHOOSE_COMPANY="CHOOSE_COMPANY"; PHONE_INPUT="PHONE_INPUT"; PHONE_CONFIRM="PHONE_CONFIRM"
    PHONE_ACTION="PHONE_ACTION"; PAYMENT_METHOD="PAYMENT_METHOD"; PAYMENT_REFERENCE="PAYMENT_REFERENCE"; PAYMENT_PROOF="PAYMENT_PROOF"
    SUPPORT_MENU="SUPPORT_MENU"; SUPPORT_SUBJECT="SUPPORT_SUBJECT"; SUPPORT_MESSAGE="SUPPORT_MESSAGE"; SUPPORT_TICKET="SUPPORT_TICKET"; SUPPORT_TICKET_MESSAGE="SUPPORT_TICKET_MESSAGE"
    ADMIN_SEARCH="ADMIN_SEARCH"; ADMIN_REJECT_REASON="ADMIN_REJECT_REASON"; ADMIN_SETTING_VALUE="ADMIN_SETTING_VALUE"; ADMIN_SETTING_CONFIRM="ADMIN_SETTING_CONFIRM"
    ADMIN_FAQ_QUESTION="ADMIN_FAQ_QUESTION"; ADMIN_FAQ_ANSWER="ADMIN_FAQ_ANSWER"; ADMIN_FAQ_EDIT="ADMIN_FAQ_EDIT"; ADMIN_PAYMENT_ACTION="ADMIN_PAYMENT_ACTION"
    ADMIN_CUSTOMER_SEARCH="ADMIN_CUSTOMER_SEARCH"; ADMIN_PHONE_SEARCH="ADMIN_PHONE_SEARCH"; ADMIN_SUPPORT_REPLY="ADMIN_SUPPORT_REPLY"
    CUSTOMER_MODE="CUSTOMER_MODE"
